apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
  labels:
    app: $IMAGE_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $IMAGE_NAME
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: $IMAGE_NAME
          image: us-docker.pkg.dev/$GCP_PROJECT_ID/gcr.io/$IMAGE_NAME:$IMAGE_TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30