apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME
  labels:
    app: $IMAGE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
        - name: $IMAGE_NAME
          image: us-docker.pkg.dev/$GCP_PROJECT_ID/gcr.io/$IMAGE_NAME:$IMAGE_TAG
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"