apiVersion: v1
kind: Service
metadata:
  name: node-port-$IMAGE_NAME
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "lb-backend-timeout"}'
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: $IMAGE_NAME
  type: NodePort