name: Build and Deploy to GKE

on:
  push:
    branches: [develop]

env:
  IMAGE_NAME: ${{ github.repository }}
  REGION: us-west1
  GKE_CLUSTER_NAME: traxion-dev
  GCP_PROJECT_ID: traxion-farma-gob-dev

jobs:
  build-and-deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_NAME env var to repo name
        run: echo "IMAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/gcr.io/${{ env.IMAGE_NAME }}:$GITHUB_SHA .
          docker push us-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/gcr.io/${{ env.IMAGE_NAME }}:$GITHUB_SHA

      - name: Install kubectl and auth plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin kubectl

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.GCP_PROJECT_ID }}

      - name: Render deployment.yaml with envsubst
        run: |
          envsubst < kubernetes.yaml > deployment-rendered.yaml
          cat deployment-rendered.yaml
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment-rendered.yaml